import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(req: Request) {
  try {
    const body = await req.json();

    const {
      revenueGap,
      ordersNeeded,
      leadsNeeded,
      bottleneck,
      priority_this_week,
      risk_warning,
    } = body;

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const margin = 60;
    const maxWidth = 475;
    let y = 780;

    const primaryColor = rgb(0.12, 0.12, 0.12);
    const accentColor = rgb(0.22, 0.35, 0.75); // subtle blue

    const drawLine = () => {
      page.drawLine({
        start: { x: margin, y },
        end: { x: 535, y },
        thickness: 1,
        color: rgb(0.85, 0.85, 0.85),
      });
      y -= 20;
    };

    const drawParagraph = (
      text: string,
      size = 12,
      bold = false,
      color = primaryColor
    ) => {
      if (!text) return;

      const safeText = text.replace(/₹/g, "Rs");
      const words = safeText.split(" ");
      let line = "";

      for (let i = 0; i < words.length; i++) {
        const testLine = line + words[i] + " ";
        const textWidth = font.widthOfTextAtSize(testLine, size);

        if (textWidth > maxWidth && i > 0) {
          page.drawText(line, {
            x: margin,
            y,
            size,
            font: bold ? boldFont : font,
            color,
          });
          line = words[i] + " ";
          y -= size + 6;
        } else {
          line = testLine;
        }
      }

      page.drawText(line, {
        x: margin,
        y,
        size,
        font: bold ? boldFont : font,
        color,
      });

      y -= size + 14;
    };

    // ===== HEADER =====
    drawParagraph("Business Revenue Diagnosis", 22, true, accentColor);
    drawParagraph("Structured growth clarity for ambitious businesses", 10);
    y -= 10;
    drawLine();

    // ===== METRICS =====
    drawParagraph("Financial Snapshot", 14, true);
    drawParagraph(`Revenue Gap: Rs ${revenueGap}`);
    drawParagraph(`Orders Needed: ${ordersNeeded}`);
    drawParagraph(`Leads Needed: ${leadsNeeded}`);
    drawLine();

    // ===== BOTTLENECK =====
    drawParagraph("Main Bottleneck", 14, true);
    drawParagraph(bottleneck);
    drawLine();

    // ===== PRIORITIES =====
    drawParagraph("Priority This Week", 14, true);

    if (Array.isArray(priority_this_week)) {
      priority_this_week.forEach((item: string, index: number) => {
        drawParagraph(`${index + 1}. ${item}`);
      });
    }

    drawLine();

    // ===== RISK =====
    drawParagraph("Risk Warning", 14, true);
    drawParagraph(risk_warning);

    // ===== FOOTER =====
    page.drawLine({
      start: { x: margin, y: 60 },
      end: { x: 535, y: 60 },
      thickness: 1,
      color: rgb(0.9, 0.9, 0.9),
    });

    page.drawText("Generated by Business Bhaiya", {
      x: margin,
      y: 40,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(pdfBytes as any, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition":
          "attachment; filename=Business_Diagnosis.pdf",
      },
    });
  } catch (error) {
    console.error("PDF Error:", error);
    return NextResponse.json(
      { error: "PDF generation failed" },
      { status: 500 }
    );
  }
}